# config.yml
database:
  host: "127.0.0.1"
  port: 27017
  user: ""
  password: ""
  db: "rpg"

bot:
  name: "Deep Requiem"
  icon_url: "https://pp.userapi.com/c844418/v844418281/1b87d4/1Ad2a7zIVZ0.jpg"

race_attrs:
  argonian:
    main:
      health_max: 105
      magicka_max: 90
      stamina_max: 120
      health_regen: 0.0
      magicka_regen: 1.1
      stamina_regen: 1.6
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 0.0
      disease_resist: 0.25
  breton:
    main:
      health_max: 90
      magicka_max: 120
      stamina_max: 90
      health_regen: 0
      magicka_regen: 1.3
      stamina_regen: 1.5
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 0.9
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 1.0
  dunmer:
    main:
      health_max: 100
      magicka_max: 100
      stamina_max: 100
      health_regen: 0
      magicka_regen: 1.25
      stamina_regen: 1.6
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 0.5
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 1.0
  altmer:
    main:
      health_max: 90
      magicka_max: 130
      stamina_max: 80
      health_regen: 0
      magicka_regen: 2.0
      stamina_regen: 1.5
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.2
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 0.25
  imperial:
    main:
      health_max: 110
      magicka_max: 100
      stamina_max: 110
      health_regen: 0
      magicka_regen: 1.1
      stamina_regen: 1.5
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 1.0
  khajit:
    main:
      health_max: 90
      magicka_max: 90
      stamina_max: 120
      health_regen: 0
      magicka_regen: 1.0
      stamina_regen: 1.65
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 1.0
  nord:
    main:
      health_max: 120
      magicka_max: 80
      stamina_max: 120
      health_regen: 0
      magicka_regen: 1.05
      stamina_regen: 1.65
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 0.65
      shock_resist: 0.85
      poison_resist: 1.0
      disease_resist: 1.0
  orc:
    main:
      health_max: 130
      magicka_max: 60
      stamina_max: 110
      health_regen: 0
      magicka_regen: 1.0
      stamina_regen: 1.7
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 0.95
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 1.0
  redguard:
    main:
      health_max: 110
      magicka_max: 70
      stamina_max: 120
      health_regen: 0
      magicka_regen: 1.0
      stamina_regen: 1.65
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 0.4
      disease_resist: 0.25
  bosmer:
    main:
      health_max: 90
      magicka_max: 110
      stamina_max: 120
      health_regen: 0
      magicka_regen: 1.05
      stamina_regen: 1.65
      health_buff: 0
      stamina_buff: 0
      magicka_buff: 0
    resists:
      magic_resist: 1.0
      fire_resist: 1.0
      frost_resist: 1.0
      shock_resist: 1.0
      poison_resist: 1.0
      disease_resist: 0.25
