# config.yml
database:
  host: "127.0.0.1"
  port: 27017
  user: ""
  password: ""
  db: "rpg"
bot:
  name: "Deep Requiem"
  icon_url: "https://pp.userapi.com/c844418/v844418281/1b87d4/1Ad2a7zIVZ0.jpg"